class TreatmentPreset {
  const TreatmentPreset({required this.name, required this.price});

  final String name;
  final double price;
}

const List<TreatmentPreset> kReceivedTreatmentsPreset = [
  TreatmentPreset(name: 'Ventana quirurgica orto Implante', price: 120),
  TreatmentPreset(name: 'Puente de 2 piezas de zirconio-cerámica', price: 780),
  TreatmentPreset(name: 'Puente de 2 piezas metal', price: 600),
  TreatmentPreset(name: 'Puente de 3 piezas de zirconio', price: 1170),
  TreatmentPreset(name: 'Puente de 3 piezas metal-cerámica', price: 900),
  TreatmentPreset(name: 'Puente de 4 piezas de zirconio', price: 1560),
  TreatmentPreset(name: 'Puente de 4 piezas metal-cerámica', price: 1200),
  TreatmentPreset(name: 'Puente de 5 piezas de zirconio', price: 1950),
  TreatmentPreset(name: 'Puente de 5 piezas metal-cerámica', price: 1500),
  TreatmentPreset(name: 'Puente de 6 piezas de zirconio', price: 2340),
  TreatmentPreset(
    name: 'Puente fijo 12 piezas sobre 6 implantes',
    price: 3400,
  ),
  TreatmentPreset(name: 'Abrasion para obturar', price: 40),
  TreatmentPreset(name: 'Aditamento de teflon', price: 50),
  TreatmentPreset(name: 'Aditamento externo', price: 100),
  TreatmentPreset(name: 'Aditamento para implante integrado', price: 300),
  TreatmentPreset(name: 'Apicectomía', price: 180),
  TreatmentPreset(name: 'Ataches', price: 240),
  TreatmentPreset(name: 'Atención domiciliaria', price: 200),
  TreatmentPreset(name: 'Blanqueamiento externo', price: 300),
  TreatmentPreset(name: 'Blanqueamiento interno', price: 100),
  TreatmentPreset(name: 'Brakets de zafiro', price: 850),
  TreatmentPreset(name: 'Brackets metalicos', price: 650),
  TreatmentPreset(name: 'Brackets transparentes', price: 700),
  TreatmentPreset(name: 'Carilla de zirconio', price: 420),
  TreatmentPreset(name: 'Cementado', price: 20),
  TreatmentPreset(name: 'Cirugia menor', price: 40),
  TreatmentPreset(name: 'Compostura', price: 60),
  TreatmentPreset(name: 'Corona metal-ceramica', price: 300),
  TreatmentPreset(name: 'Corona sobre implante', price: 450),
  TreatmentPreset(name: 'Corona zirconio', price: 390),
  TreatmentPreset(
    name: 'Desatornillar protesis y limpieza de implantes',
    price: 75,
  ),
  TreatmentPreset(name: 'Diferencia de reconstruccion', price: 20),
  TreatmentPreset(name: 'Elevacion con regeneración', price: 900),
  TreatmentPreset(name: 'Elevacion de seno', price: 500),
  TreatmentPreset(name: 'Empaste', price: 50),
  TreatmentPreset(name: 'Endodoncia multirradicular', price: 180),
  TreatmentPreset(name: 'Endodoncia unirradicular', price: 150),
  TreatmentPreset(name: 'Estudio de ortodoncia', price: 50),
  TreatmentPreset(name: 'Exodoncia compleja', price: 120),
  TreatmentPreset(name: 'Exodoncia de tercer molar', price: 100),
  TreatmentPreset(name: 'Exodoncia normal', price: 50),
  TreatmentPreset(name: 'Férula de descarga michigan', price: 250),
  TreatmentPreset(name: 'Ferula retenedora de alambre', price: 120),
  TreatmentPreset(name: 'Ferula retenedora de ortodoncia', price: 100),
  TreatmentPreset(name: 'Frenectomia', price: 180),
  TreatmentPreset(name: 'Gingivectomia', price: 180),
  TreatmentPreset(name: 'Gran reconstrucción', price: 80),
  TreatmentPreset(name: 'Implante', price: 890),
  TreatmentPreset(name: 'Injerto de tejido conectivo', price: 500),
  TreatmentPreset(name: 'Limpieza', price: 60),
  TreatmentPreset(name: 'Mantenedor de espacio', price: 120),
  TreatmentPreset(name: 'Mesoestructura completa', price: 4200),
  TreatmentPreset(name: 'Perno de cuarzo', price: 100),
  TreatmentPreset(name: 'Perno de titanio', price: 90),
  TreatmentPreset(name: 'Piercing', price: 40),
  TreatmentPreset(name: 'Placa expansora', price: 500),
  TreatmentPreset(name: 'Placa Hawley', price: 400),
  TreatmentPreset(name: 'Protesis de metal-esquelético', price: 800),
  TreatmentPreset(name: 'Protesis de resina', price: 700),
  TreatmentPreset(name: 'Protesis imediata completa', price: 350),
  TreatmentPreset(name: 'Protesis inmediata parcial', price: 250),
  TreatmentPreset(name: 'Raspaje y alisado por cuadrante', price: 80),
  TreatmentPreset(name: 'Raspaje y alisado por pieza', price: 20),
  TreatmentPreset(name: 'Reconstrucción endodoncia', price: 60),
  TreatmentPreset(name: 'Reconstrucción estética', price: 120),
  TreatmentPreset(name: 'Regeneracion osea', price: 450),
  TreatmentPreset(name: 'Regularización ósea', price: 200),
  TreatmentPreset(name: 'Rehacer endodoncia', price: 180),
  TreatmentPreset(name: 'Reponer empaste', price: 25),
  TreatmentPreset(name: 'Revision placa Hawley', price: 30),
  TreatmentPreset(name: 'Revision placa expansora', price: 50),
  TreatmentPreset(name: 'Sellador', price: 20),
  TreatmentPreset(name: 'Sobredentadura', price: 900),
  TreatmentPreset(name: 'Sobredentadura removible', price: 2340),
  TreatmentPreset(
    name: 'Tratamiento de ortodoncia de 12 meses',
    price: 1080,
  ),
  TreatmentPreset(
    name: 'Tratamiento de ortodoncia de 18 meses',
    price: 1620,
  ),
  TreatmentPreset(
    name: 'Tratamiento de ortodoncia de 24 meses',
    price: 2160,
  ),
  TreatmentPreset(
    name: 'Tratamiento de ortodoncia con smilers de 18 meses',
    price: 6300,
  ),
  TreatmentPreset(
    name: 'Tratamiento de ortodoncia con smilers de 12 meses',
    price: 4200,
  ),
  TreatmentPreset(
    name: 'Tratamiento de ortodoncia con smilers de 6 meses',
    price: 2100,
  ),
];
